"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ti404 = exports.ecs404 = exports.setup404 = exports.images404 = exports.css404 = exports.js404 = exports.staticcdn404 = exports.api404 = exports.www404 = void 0;
const www_1 = __importDefault(require("./www"));
const api_1 = __importDefault(require("./api"));
const staticcdn_1 = __importDefault(require("./staticcdn"));
const js_1 = __importDefault(require("./js"));
const css_1 = __importDefault(require("./css"));
const images_1 = __importDefault(require("./images"));
const setup_1 = __importDefault(require("./setup"));
const ecs_1 = __importDefault(require("./ecs"));
const ti_1 = __importDefault(require("./ti"));
exports.www404 = www_1.default;
exports.api404 = api_1.default;
exports.staticcdn404 = staticcdn_1.default;
exports.js404 = js_1.default;
exports.css404 = css_1.default;
exports.images404 = images_1.default;
exports.setup404 = setup_1.default;
exports.ecs404 = ecs_1.default;
exports.ti404 = ti_1.default;
