import { IEmail } from '../Credentials/IEmail';
import { IPassword } from '../Credentials/IPassword';
import { IUser } from './IUser';
import { UserModelBuildersClubMembershipTypeEnum } from './UserModelBuildersClubMembershipTypeEnum';
export declare class User implements IUser {
    Id: Number;
    Name: String;
    DisplayName: String;
    MembershipType: UserModelBuildersClubMembershipTypeEnum;
    SecurityToken: String;
    Description: String;
    Password: IPassword;
    Created: String;
    IsBanned: Boolean;
    Email: IEmail;
    HasPasswordSet: Boolean;
    AgeBracket: Number;
    Roles: String[];
    RobuxBalance: Number;
    NotificationCount: Number;
    EmailNotificationsEnabled: Boolean;
    CountryCode: String;
    UserAbove13: Boolean;
    ThumbnailUrl: String;
    IsAnyBuildersClubMember: Boolean;
    IsPremium: Boolean;
    ChangeUsernameEnabled: Boolean;
    IsAdmin: Boolean;
    static GetByUserId(Id: number): IUser;
}
