INSERT INTO 
`robloxmembership`.`user` 
(
	`Id`,
	`Name`,
	`DisplayName`,
	`MembershipType`,
	`Description`,
	`Created`,
	`Updated`,
	`IsBanned`,
    `AgeBracket`,
    `Roles`,
    `CountryCode`,
    `UserAbove13`,
    `IsAdmin`, 
    `AccountId`
) VALUES 
(
	'USER_ID',
    'USER_NAME',
    'DISPLAY_NAME',
    'MEMBERSHIP_TYPE',
    'DESCRIPTION',
    'CREATED_DATE',
    'UPDATED_DATE',
    'IS_BANNED',
    'AGE_BRACKET',
    'ROLES',
    'LOCALE_ID',
    'USER_ABOVE_13',
    'IS_ADMIN',
    'ACCOUNT_ID'
);