/*
	FileName: Roblox.SSL.ts
	Written By: Nikita Nikolaevich Petko
	File Type: Module
	Description: Wrapper for SSL servers and https servers, used as a helper.

	All commits will be made on behalf of mfd-co to https://github.com/mfd-core/sitetest4.robloxlabs.com

	***

	Copyright 2006-2021 ROBLOX

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	https://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

	***
*/

import https2 from 'spdy';
import { Express as IApplicationBuilder } from 'express-serve-static-core';
import { Server as httpserver } from 'http';
import { Server as httpsServer } from 'https';
import dotenv from 'dotenv';
import filestream from 'fs';
import { FASTLOG2, SFLog, SYNCHRONIZED_LOGGROUP } from '../Roblox.Util/Roblox.Util.FastLog';
import { _dirname, _sslname } from '../../Constants/Directories';
import Urls from '../../Constants/Urls';

dotenv.config({ path: _dirname + '\\.env' });

SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_WWW']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_API']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_STATIC_CDN']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_JS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CSS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_IMAGES']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_SETUP_CDN']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_EPHEMERAL_COUNTERS_API']);
SYNCHRONIZED_LOGGROUP(Urls['DEPRECATED_ROBLOX_TEMPORARY_IMAGES']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_VERSION_COMPATIBILITY_API']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CLIENT_SETTINGS_API']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_ASSET_GAME']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_EPHEMERAL_COUNTERS_VERSION_2']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_GAME_PERSISTENCE']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_DOSARREST_ORIGIN_CORP']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_MARKETPLACE_API']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_METRICS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_AUTH']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_APIS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_LOCALE']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_AB_TESTING']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_AB_TESTING_API']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_USERS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_TWO_STEP_VERIFICATION']);
SYNCHRONIZED_LOGGROUP(Urls['SIMULPONG_LATENCY_MEASUREMENTS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CHAT']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CONTACTS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_NOTIFICATIONS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_ACCOUNT_SETTINGS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_ADS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_TRADES']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_FRIENDS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_PRIVATE_MESSAGES']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_ECONOMY']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_GAMES']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_REAL_TIME']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_THUMB_NAILS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_PRESENCE']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_GROUPS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_ACCOUNT_INFORMATION']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_BADGES']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_DEVELOPER_FORUM']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_PREMIUM_FEATURES']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CLIENT_SETTINGS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CLIENT_SETTINGS_CDN']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_AD_CONFIGURATION']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CLIENT_TELEMENTRY']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_ASSET_DELIVERY']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_AVATAR']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_BILLING']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CATALOG']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CDN_PROVIDERS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CHAT_MODERATION']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_CONTENT_STORE']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_DEVELOP']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_DISCUSSIONS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_ECONOMY_CREATOR_STATS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_ENGAGEMENT_PAYOUTS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_FOLLOWINGS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_GAME_INTERNATIONALIZATION']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_GAME_JOIN']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_GROUPS_MODERATION']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_INVENTORY']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_ITEM_CONFIGURATION']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_LOCALIZATION_TABLES']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_POINTS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_PUBLISH']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_PUNISHMENTS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_SHARE']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_TEXT_FILTER']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_THEMES']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_THUMBNAILS_RESIZER']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_TRANSLATION_ROLES']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_TRANSLATIONS']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_USER_MODERATION']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_VOICE']);
SYNCHRONIZED_LOGGROUP(Urls['ROBLOX_FILES_API']);
SYNCHRONIZED_LOGGROUP(Urls['SIMULPONG_ROBLOX_TEAM_CITY']);

export const ROBLOX_Starter = (app: IApplicationBuilder, name: string): [httpserver, httpsServer] => {
	try {
		const httpsServer = https2
			.createServer(
				{
					cert: filestream.readFileSync(_sslname + '\\ST4.crt', 'utf-8'),
					key: filestream.readFileSync(_sslname + '\\ST4.key', 'utf-8'),
					passphrase: process.env['ST4_pw'],
				},
				app,
			)
			.listen(443, name, () => FASTLOG2(SFLog[name], `[SFLog::%s] https://%s:443 Started`, name, name));
		const httpServer = app.listen(80, name, () => FASTLOG2(SFLog[name], `[SFLog::%s] http://%s:80 Started`, name, name));
		return [httpServer, httpsServer];
	} catch (err) {
		throw new Error(err);
	}
};
